/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConquistaDAO;
import DTO.ConquistaDTO;

/**
 *
 * @author Isabella
 */
public class frmCriarConquista extends javax.swing.JFrame {

    /**
     * Creates new form frmCriarConquista
     */
    public frmCriarConquista() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initComponents();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idConquista = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        tituloConquista = new javax.swing.JTextField();
        dadoConquista = new javax.swing.JTextField();
        descricaoConquista = new javax.swing.JTextField();
        tipoConquista = new javax.swing.JTextField();
        criar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        pesquisar.setBackground(new java.awt.Color(0, 153, 204));
        pesquisar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        pesquisar.setForeground(new java.awt.Color(51, 51, 51));
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConquistaDAO conquistaDAO = new ConquistaDAO();
                if(idConquista.getText() != null) {
                    try {
                        ConquistaDTO conquistaDTO = new ConquistaDTO();
                        conquistaDTO = conquistaDAO.getConquistaById(Integer.parseInt(idConquista.getText()));
                        if(conquistaDTO != null) {
                            dadoConquista.setText(String.valueOf(conquistaDTO.getDadoConquista()));
                            tipoConquista.setText(String.valueOf(conquistaDTO.getTipoConquista()));
                            tituloConquista.setText(conquistaDTO.getTitulo());
                            descricaoConquista.setText(conquistaDTO.getDescricao());
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        getContentPane().add(pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 100, 80, -1));

        idConquista.setBackground(new java.awt.Color(36, 58, 115));
        idConquista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Conquista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(idConquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 220, -1));
        
        dadoConquista.setBackground(new java.awt.Color(51, 51, 51));
        dadoConquista.setForeground(new java.awt.Color(255, 255, 204));
        dadoConquista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dado Conquista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        getContentPane().add(dadoConquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, -1));

        tipoConquista.setBackground(new java.awt.Color(51, 51, 51));
        tipoConquista.setForeground(new java.awt.Color(255, 255, 204));
        tipoConquista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Conquista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        getContentPane().add(tipoConquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, -1));

        tituloConquista.setBackground(new java.awt.Color(51, 51, 51));
        tituloConquista.setForeground(new java.awt.Color(255, 255, 204));
        tituloConquista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Título Conquista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        getContentPane().add(tituloConquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 200, -1));

        descricaoConquista.setBackground(new java.awt.Color(51, 51, 51));
        descricaoConquista.setForeground(new java.awt.Color(255, 255, 204));
        descricaoConquista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição Conquista:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        getContentPane().add(descricaoConquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 200, -1));

        criar.setBackground(new java.awt.Color(0, 153, 204));
        criar.setText("Criar/ Atualizar");
        criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConquistaDAO conquistaDAO = new ConquistaDAO();
                if(conquistaDAO.conquistaExists(Integer.parseInt(idConquista.getText()))) {
                    conquistaDAO.updateConquista(Integer.parseInt(idConquista.getText()), Double.parseDouble(dadoConquista.getText()), Boolean.parseBoolean(tipoConquista.getText()), tituloConquista.getText(), descricaoConquista.getText());
                } else {
                    conquistaDAO.createConquista(Double.parseDouble(dadoConquista.getText()), Boolean.parseBoolean(tipoConquista.getText()), tituloConquista.getText(), descricaoConquista.getText());
                }
                frmCriarConquista.this.dispose();
            }
        });
        getContentPane().add(criar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, 30));

        jButton1 = new javax.swing.JButton();
        jButton1.setBackground(new java.awt.Color(200, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmCriarConquista.this.dispose();
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/perfil.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCriarConquista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCriarConquista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton criar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField idConquista;
    private javax.swing.JTextField dadoConquista;
    private javax.swing.JTextField descricaoConquista;
    private javax.swing.JTextField tipoConquista;
    private javax.swing.JTextField tituloConquista;
    // End of variables declaration//GEN-END:variables
}
